apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-model
  name: data-model-arrival
spec:
  volumes:
    - name: ch-data
      hostPath:
        path: /PigeonRacing/src/data_preprocess/data
        type: Directory
    - name: models
      hostPath:
        path: /PigeonRacing/src/data_train/pre-trained
        type: Directory
  containers:
  - args:
    - python
    - src/data_train/models/arrival.py
    image: dylanzammit/pigeon-data-model:latest  # avoid using latest
    name: data-model-arrival
    env:
      - name: MLFLOW_EXPERIMENT_NAME
        value: arrival
    # imagePullPolicy: IfNotPresent  # use once latest is removed
    resources:
      requests:
        memory: "4Gi"
        cpu: 2
    volumeMounts:
      - name: ch-data
        mountPath: src/data_preprocess/data
      - name: models
        mountPath: src/data_train/pre-trained
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
