apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mlflow
  name: mlflow
spec:
  volumes:
    - name: models
      hostPath:
        path: /PigeonRacing/src/data_train/pre-trained
        type: Directory
  containers:
  - args:
    image: atcommons/mlflow-server:1.20.0
    name: mlflow
    ports:
      - containerPort: 5000
        name: http
    env:
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
        value: python
    # imagePullPolicy: IfNotPresent  # use once latest is removed
    resources:
      requests:
        memory: "1Gi"
        cpu: 2
    volumeMounts:
      - name: models
        mountPath: src/data_train/pre-trained
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
