apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: clickhouse
  name: clickhouse
spec:
  ports:
  - name: 18123-8123
    port: 18123
    protocol: TCP
    targetPort: 8123
  selector:
    app: clickhouse
  type: ClusterIP
status:
  loadBalancer: {}
