pred_col: velocity
train_start: 2018-01-01
train_end: 2023-01-01
model_params:
  boosting_type: 'gbdt'
  objective: 'regression'
  # 'metric':metrics,
  learning_rate: 0.1
  metric: 'rmse'

  # 'is_unbalance': 'true',  #because training data is unbalance (replaced with scale_pos_weight)
  num_leaves: 31  # we should let it be smaller than 2^(max_depth)
  max_depth: -1  # -1 means no limit
  min_child_samples: 10  # Minimum number of data need in a child(min_data_in_leaf)
  max_bin: 255  # Number of bucketed bin for feature values
  subsample: 0.2  # Subsample ratio of the training instance.
  subsample_freq: 0  # frequence of subsample, <=0 means no enable
  colsample_bytree: 0.6  # Subsample ratio of columns when constructing each tree.
  min_child_weight: 5  # Minimum sum of instance weight(hessian) needed in a child(leaf)
  subsample_for_bin: 200_000  # Number of samples for constructing bin
  min_split_gain: 0  # lambda_l1, lambda_l2 and min_gain_to_split to regularization
  reg_alpha: 0  # L1 regularization term on weights
  reg_lambda: 0  # L2 regularization term on weights
  nthread: 4
  verbose: 0
  n_estimators: 100
  # 'scale_pos_weight': 0.5???,
features:
  covariates:
    - temperature_departure
    - temperature_malta

    - dew_point_departure
    - dew_point_malta

    - distance_race_points

    - relative_humidity_departure
    - relative_humidity_malta
    - relative_humidity_sicily

    # TODO: check why being NaN
    # 'precipitation_malta',
    # 'precipitation_departure',

    - wind_direction_degrees_departure
    - wind_direction_degrees_malta
    - wind_direction_degrees_sicily

    - wind_speed_kph_departure
    - wind_speed_kph_malta
    - wind_speed_kph_sicily

    - air_pressure_departure
    - air_pressure_malta
    - air_pressure_sicily

    - wind_speed_beaufort_sicily
    - wind_speed_beaufort_malta
    - wind_speed_beaufort_departure

    - current_level
    - last_year_level

    - race_count
    - velocity_form
    - velocity_lag
    - velocity_form_linear

    - registered_pigeons
    - release_hour

  categorical:
    - race_point_name
    - wind_direction_compass_sicily
    - wind_direction_compass_malta
    - wind_direction_compass_departure
    - release_month
    - race_name
    - race_point_types
    - pigeon_id